/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QTokenRouteImport } from './routes/q.$token'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppQuotationsIndexRouteImport } from './routes/_app/quotations.index'
import { Route as AppProductsIndexRouteImport } from './routes/_app/products.index'
import { Route as AppCustomersIndexRouteImport } from './routes/_app/customers.index'
import { Route as AppQuotationsNewRouteImport } from './routes/_app/quotations.new'
import { Route as AppQuotationsQuotationIdRouteImport } from './routes/_app/quotations.$quotationId'
import { Route as AppProductsNewRouteImport } from './routes/_app/products.new'
import { Route as AppProductsCategoriesRouteImport } from './routes/_app/products.categories'
import { Route as AppProductsProductIdRouteImport } from './routes/_app/products.$productId'
import { Route as AppCustomersNewRouteImport } from './routes/_app/customers.new'
import { Route as AppCustomersCustomerIdRouteImport } from './routes/_app/customers.$customerId'
import { Route as AppQuotationsQuotationIdPrintRouteImport } from './routes/_app/quotations.$quotationId.print'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QTokenRoute = QTokenRouteImport.update({
  id: '/q/$token',
  path: '/q/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotationsIndexRoute = AppQuotationsIndexRouteImport.update({
  id: '/quotations/',
  path: '/quotations/',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotationsNewRoute = AppQuotationsNewRouteImport.update({
  id: '/quotations/new',
  path: '/quotations/new',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotationsQuotationIdRoute =
  AppQuotationsQuotationIdRouteImport.update({
    id: '/quotations/$quotationId',
    path: '/quotations/$quotationId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProductsNewRoute = AppProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsCategoriesRoute = AppProductsCategoriesRouteImport.update({
  id: '/products/categories',
  path: '/products/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsProductIdRoute = AppProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersNewRoute = AppCustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersCustomerIdRoute = AppCustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotationsQuotationIdPrintRoute =
  AppQuotationsQuotationIdPrintRouteImport.update({
    id: '/print',
    path: '/print',
    getParentRoute: () => AppQuotationsQuotationIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/audit': typeof AppAuditRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/q/$token': typeof QTokenRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/customers/new': typeof AppCustomersNewRoute
  '/products/$productId': typeof AppProductsProductIdRoute
  '/products/categories': typeof AppProductsCategoriesRoute
  '/products/new': typeof AppProductsNewRoute
  '/quotations/$quotationId': typeof AppQuotationsQuotationIdRouteWithChildren
  '/quotations/new': typeof AppQuotationsNewRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/products/': typeof AppProductsIndexRoute
  '/quotations/': typeof AppQuotationsIndexRoute
  '/quotations/$quotationId/print': typeof AppQuotationsQuotationIdPrintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/audit': typeof AppAuditRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/q/$token': typeof QTokenRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/customers/new': typeof AppCustomersNewRoute
  '/products/$productId': typeof AppProductsProductIdRoute
  '/products/categories': typeof AppProductsCategoriesRoute
  '/products/new': typeof AppProductsNewRoute
  '/quotations/$quotationId': typeof AppQuotationsQuotationIdRouteWithChildren
  '/quotations/new': typeof AppQuotationsNewRoute
  '/customers': typeof AppCustomersIndexRoute
  '/products': typeof AppProductsIndexRoute
  '/quotations': typeof AppQuotationsIndexRoute
  '/quotations/$quotationId/print': typeof AppQuotationsQuotationIdPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/q/$token': typeof QTokenRoute
  '/_app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/_app/customers/new': typeof AppCustomersNewRoute
  '/_app/products/$productId': typeof AppProductsProductIdRoute
  '/_app/products/categories': typeof AppProductsCategoriesRoute
  '/_app/products/new': typeof AppProductsNewRoute
  '/_app/quotations/$quotationId': typeof AppQuotationsQuotationIdRouteWithChildren
  '/_app/quotations/new': typeof AppQuotationsNewRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/products/': typeof AppProductsIndexRoute
  '/_app/quotations/': typeof AppQuotationsIndexRoute
  '/_app/quotations/$quotationId/print': typeof AppQuotationsQuotationIdPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/audit'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/q/$token'
    | '/customers/$customerId'
    | '/customers/new'
    | '/products/$productId'
    | '/products/categories'
    | '/products/new'
    | '/quotations/$quotationId'
    | '/quotations/new'
    | '/customers/'
    | '/products/'
    | '/quotations/'
    | '/quotations/$quotationId/print'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/audit'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/q/$token'
    | '/customers/$customerId'
    | '/customers/new'
    | '/products/$productId'
    | '/products/categories'
    | '/products/new'
    | '/quotations/$quotationId'
    | '/quotations/new'
    | '/customers'
    | '/products'
    | '/quotations'
    | '/quotations/$quotationId/print'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_app/audit'
    | '/_app/dashboard'
    | '/_app/profile'
    | '/_app/settings'
    | '/q/$token'
    | '/_app/customers/$customerId'
    | '/_app/customers/new'
    | '/_app/products/$productId'
    | '/_app/products/categories'
    | '/_app/products/new'
    | '/_app/quotations/$quotationId'
    | '/_app/quotations/new'
    | '/_app/customers/'
    | '/_app/products/'
    | '/_app/quotations/'
    | '/_app/quotations/$quotationId/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  QTokenRoute: typeof QTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/$token': {
      id: '/q/$token'
      path: '/q/$token'
      fullPath: '/q/$token'
      preLoaderRoute: typeof QTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotations/': {
      id: '/_app/quotations/'
      path: '/quotations'
      fullPath: '/quotations/'
      preLoaderRoute: typeof AppQuotationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotations/new': {
      id: '/_app/quotations/new'
      path: '/quotations/new'
      fullPath: '/quotations/new'
      preLoaderRoute: typeof AppQuotationsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotations/$quotationId': {
      id: '/_app/quotations/$quotationId'
      path: '/quotations/$quotationId'
      fullPath: '/quotations/$quotationId'
      preLoaderRoute: typeof AppQuotationsQuotationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/new': {
      id: '/_app/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AppProductsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/categories': {
      id: '/_app/products/categories'
      path: '/products/categories'
      fullPath: '/products/categories'
      preLoaderRoute: typeof AppProductsCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/$productId': {
      id: '/_app/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AppProductsProductIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/new': {
      id: '/_app/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof AppCustomersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/$customerId': {
      id: '/_app/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AppCustomersCustomerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotations/$quotationId/print': {
      id: '/_app/quotations/$quotationId/print'
      path: '/print'
      fullPath: '/quotations/$quotationId/print'
      preLoaderRoute: typeof AppQuotationsQuotationIdPrintRouteImport
      parentRoute: typeof AppQuotationsQuotationIdRoute
    }
  }
}

interface AppQuotationsQuotationIdRouteChildren {
  AppQuotationsQuotationIdPrintRoute: typeof AppQuotationsQuotationIdPrintRoute
}

const AppQuotationsQuotationIdRouteChildren: AppQuotationsQuotationIdRouteChildren =
  {
    AppQuotationsQuotationIdPrintRoute: AppQuotationsQuotationIdPrintRoute,
  }

const AppQuotationsQuotationIdRouteWithChildren =
  AppQuotationsQuotationIdRoute._addFileChildren(
    AppQuotationsQuotationIdRouteChildren,
  )

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppCustomersCustomerIdRoute: typeof AppCustomersCustomerIdRoute
  AppCustomersNewRoute: typeof AppCustomersNewRoute
  AppProductsProductIdRoute: typeof AppProductsProductIdRoute
  AppProductsCategoriesRoute: typeof AppProductsCategoriesRoute
  AppProductsNewRoute: typeof AppProductsNewRoute
  AppQuotationsQuotationIdRoute: typeof AppQuotationsQuotationIdRouteWithChildren
  AppQuotationsNewRoute: typeof AppQuotationsNewRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
  AppQuotationsIndexRoute: typeof AppQuotationsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppCustomersCustomerIdRoute: AppCustomersCustomerIdRoute,
  AppCustomersNewRoute: AppCustomersNewRoute,
  AppProductsProductIdRoute: AppProductsProductIdRoute,
  AppProductsCategoriesRoute: AppProductsCategoriesRoute,
  AppProductsNewRoute: AppProductsNewRoute,
  AppQuotationsQuotationIdRoute: AppQuotationsQuotationIdRouteWithChildren,
  AppQuotationsNewRoute: AppQuotationsNewRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
  AppQuotationsIndexRoute: AppQuotationsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  QTokenRoute: QTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
